### PR TITLE
👌 Add OUTPUT_FILE option

### PR DESCRIPTION
**Pull request by tommy-anderson**
I found it useful to have a separate output file for the timings so that I can avoid overriding the SPLIT_FILE with new timings. Thought it would be nice to add it to the main repo

### CODE REVIEW

**Comment by tommy-anderson** [comment]
@bahmutov any feedback on this proposal?

**Comment by bahmutov** [comment]
I like it. A couple of additions:
- rename `OUTPUT_FILE` to `SPLIT_OUTPUT_FILE`
- add labels to the new `console.log` statements so it is clear where the messages are coming from
- add a test job that just shows it in action, ok

**Comment by tommy-anderson** [comment]
Implemented PR feedback, please review

**Review by bahmutov — APPROVED** [review]
super

**Pull request merged**
